// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	flowschema "github.com/facebookincubator/symphony/pkg/flowengine/flowschema"
	mock "github.com/stretchr/testify/mock"

	triggers "github.com/facebookincubator/symphony/pkg/flowengine/triggers"
)

// Factory is an autogenerated mock type for the Factory type
type Factory struct {
	mock.Mock
}

// GetType provides a mock function with given fields: id
func (_m *Factory) GetType(id flowschema.TriggerTypeID) (triggers.TriggerType, error) {
	ret := _m.Called(id)

	var r0 triggers.TriggerType
	if rf, ok := ret.Get(0).(func(flowschema.TriggerTypeID) triggers.TriggerType); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(triggers.TriggerType)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(flowschema.TriggerTypeID) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
