// Copyright (c) 2004-present Facebook All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/facebook/ent/dialect/sql/sqlgraph"
	"github.com/facebook/ent/schema/field"
	"github.com/facebookincubator/symphony/pkg/ent/parametercatalog"
	"github.com/facebookincubator/symphony/pkg/ent/propertycategory"
)

// ParameterCatalogCreate is the builder for creating a ParameterCatalog entity.
type ParameterCatalogCreate struct {
	config
	mutation *ParameterCatalogMutation
	hooks    []Hook
}

// SetCreateTime sets the create_time field.
func (pcc *ParameterCatalogCreate) SetCreateTime(t time.Time) *ParameterCatalogCreate {
	pcc.mutation.SetCreateTime(t)
	return pcc
}

// SetNillableCreateTime sets the create_time field if the given value is not nil.
func (pcc *ParameterCatalogCreate) SetNillableCreateTime(t *time.Time) *ParameterCatalogCreate {
	if t != nil {
		pcc.SetCreateTime(*t)
	}
	return pcc
}

// SetUpdateTime sets the update_time field.
func (pcc *ParameterCatalogCreate) SetUpdateTime(t time.Time) *ParameterCatalogCreate {
	pcc.mutation.SetUpdateTime(t)
	return pcc
}

// SetNillableUpdateTime sets the update_time field if the given value is not nil.
func (pcc *ParameterCatalogCreate) SetNillableUpdateTime(t *time.Time) *ParameterCatalogCreate {
	if t != nil {
		pcc.SetUpdateTime(*t)
	}
	return pcc
}

// SetName sets the name field.
func (pcc *ParameterCatalogCreate) SetName(s string) *ParameterCatalogCreate {
	pcc.mutation.SetName(s)
	return pcc
}

// SetIndex sets the index field.
func (pcc *ParameterCatalogCreate) SetIndex(i int) *ParameterCatalogCreate {
	pcc.mutation.SetIndex(i)
	return pcc
}

// SetNillableIndex sets the index field if the given value is not nil.
func (pcc *ParameterCatalogCreate) SetNillableIndex(i *int) *ParameterCatalogCreate {
	if i != nil {
		pcc.SetIndex(*i)
	}
	return pcc
}

// SetDisabled sets the disabled field.
func (pcc *ParameterCatalogCreate) SetDisabled(b bool) *ParameterCatalogCreate {
	pcc.mutation.SetDisabled(b)
	return pcc
}

// SetNillableDisabled sets the disabled field if the given value is not nil.
func (pcc *ParameterCatalogCreate) SetNillableDisabled(b *bool) *ParameterCatalogCreate {
	if b != nil {
		pcc.SetDisabled(*b)
	}
	return pcc
}

// AddPropertyCategoryIDs adds the property_categories edge to PropertyCategory by ids.
func (pcc *ParameterCatalogCreate) AddPropertyCategoryIDs(ids ...int) *ParameterCatalogCreate {
	pcc.mutation.AddPropertyCategoryIDs(ids...)
	return pcc
}

// AddPropertyCategories adds the property_categories edges to PropertyCategory.
func (pcc *ParameterCatalogCreate) AddPropertyCategories(p ...*PropertyCategory) *ParameterCatalogCreate {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return pcc.AddPropertyCategoryIDs(ids...)
}

// Mutation returns the ParameterCatalogMutation object of the builder.
func (pcc *ParameterCatalogCreate) Mutation() *ParameterCatalogMutation {
	return pcc.mutation
}

// Save creates the ParameterCatalog in the database.
func (pcc *ParameterCatalogCreate) Save(ctx context.Context) (*ParameterCatalog, error) {
	var (
		err  error
		node *ParameterCatalog
	)
	pcc.defaults()
	if len(pcc.hooks) == 0 {
		if err = pcc.check(); err != nil {
			return nil, err
		}
		node, err = pcc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ParameterCatalogMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = pcc.check(); err != nil {
				return nil, err
			}
			pcc.mutation = mutation
			node, err = pcc.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(pcc.hooks) - 1; i >= 0; i-- {
			mut = pcc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, pcc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (pcc *ParameterCatalogCreate) SaveX(ctx context.Context) *ParameterCatalog {
	v, err := pcc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// defaults sets the default values of the builder before save.
func (pcc *ParameterCatalogCreate) defaults() {
	if _, ok := pcc.mutation.CreateTime(); !ok {
		v := parametercatalog.DefaultCreateTime()
		pcc.mutation.SetCreateTime(v)
	}
	if _, ok := pcc.mutation.UpdateTime(); !ok {
		v := parametercatalog.DefaultUpdateTime()
		pcc.mutation.SetUpdateTime(v)
	}
	if _, ok := pcc.mutation.Index(); !ok {
		v := parametercatalog.DefaultIndex
		pcc.mutation.SetIndex(v)
	}
	if _, ok := pcc.mutation.Disabled(); !ok {
		v := parametercatalog.DefaultDisabled
		pcc.mutation.SetDisabled(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (pcc *ParameterCatalogCreate) check() error {
	if _, ok := pcc.mutation.CreateTime(); !ok {
		return &ValidationError{Name: "create_time", err: errors.New("ent: missing required field \"create_time\"")}
	}
	if _, ok := pcc.mutation.UpdateTime(); !ok {
		return &ValidationError{Name: "update_time", err: errors.New("ent: missing required field \"update_time\"")}
	}
	if _, ok := pcc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New("ent: missing required field \"name\"")}
	}
	if _, ok := pcc.mutation.Index(); !ok {
		return &ValidationError{Name: "index", err: errors.New("ent: missing required field \"index\"")}
	}
	if _, ok := pcc.mutation.Disabled(); !ok {
		return &ValidationError{Name: "disabled", err: errors.New("ent: missing required field \"disabled\"")}
	}
	return nil
}

func (pcc *ParameterCatalogCreate) sqlSave(ctx context.Context) (*ParameterCatalog, error) {
	_node, _spec := pcc.createSpec()
	if err := sqlgraph.CreateNode(ctx, pcc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (pcc *ParameterCatalogCreate) createSpec() (*ParameterCatalog, *sqlgraph.CreateSpec) {
	var (
		_node = &ParameterCatalog{config: pcc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: parametercatalog.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: parametercatalog.FieldID,
			},
		}
	)
	if value, ok := pcc.mutation.CreateTime(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: parametercatalog.FieldCreateTime,
		})
		_node.CreateTime = value
	}
	if value, ok := pcc.mutation.UpdateTime(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: parametercatalog.FieldUpdateTime,
		})
		_node.UpdateTime = value
	}
	if value, ok := pcc.mutation.Name(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: parametercatalog.FieldName,
		})
		_node.Name = value
	}
	if value, ok := pcc.mutation.Index(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: parametercatalog.FieldIndex,
		})
		_node.Index = value
	}
	if value, ok := pcc.mutation.Disabled(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeBool,
			Value:  value,
			Column: parametercatalog.FieldDisabled,
		})
		_node.Disabled = value
	}
	if nodes := pcc.mutation.PropertyCategoriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   parametercatalog.PropertyCategoriesTable,
			Columns: []string{parametercatalog.PropertyCategoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: propertycategory.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ParameterCatalogCreateBulk is the builder for creating a bulk of ParameterCatalog entities.
type ParameterCatalogCreateBulk struct {
	config
	builders []*ParameterCatalogCreate
}

// Save creates the ParameterCatalog entities in the database.
func (pccb *ParameterCatalogCreateBulk) Save(ctx context.Context) ([]*ParameterCatalog, error) {
	specs := make([]*sqlgraph.CreateSpec, len(pccb.builders))
	nodes := make([]*ParameterCatalog, len(pccb.builders))
	mutators := make([]Mutator, len(pccb.builders))
	for i := range pccb.builders {
		func(i int, root context.Context) {
			builder := pccb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ParameterCatalogMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, pccb.builders[i+1].mutation)
				} else {
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, pccb.driver, &sqlgraph.BatchCreateSpec{Nodes: specs}); err != nil {
						if cerr, ok := isSQLConstraintError(err); ok {
							err = cerr
						}
					}
				}
				mutation.done = true
				if err != nil {
					return nil, err
				}
				id := specs[i].ID.Value.(int64)
				nodes[i].ID = int(id)
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, pccb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX calls Save and panics if Save returns an error.
func (pccb *ParameterCatalogCreateBulk) SaveX(ctx context.Context) []*ParameterCatalog {
	v, err := pccb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}
