// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	flowschema "github.com/facebookincubator/symphony/pkg/flowengine/flowschema"
	mock "github.com/stretchr/testify/mock"
)

// TriggerType is an autogenerated mock type for the TriggerType type
type TriggerType struct {
	mock.Mock
}

// Description provides a mock function with given fields:
func (_m *TriggerType) Description() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// ID provides a mock function with given fields:
func (_m *TriggerType) ID() flowschema.TriggerTypeID {
	ret := _m.Called()

	var r0 flowschema.TriggerTypeID
	if rf, ok := ret.Get(0).(func() flowschema.TriggerTypeID); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(flowschema.TriggerTypeID)
	}

	return r0
}

// Variables provides a mock function with given fields:
func (_m *TriggerType) Variables() []*flowschema.VariableDefinition {
	ret := _m.Called()

	var r0 []*flowschema.VariableDefinition
	if rf, ok := ret.Get(0).(func() []*flowschema.VariableDefinition); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*flowschema.VariableDefinition)
		}
	}

	return r0
}
