#!/usr/bin/env python3
# @generated AUTOGENERATED file. Do not Change!

from dataclasses import dataclass, field as _field
from functools import partial
from ...config import custom_scalars, datetime
from numbers import Number
from typing import Any, AsyncGenerator, Dict, List, Generator, Optional

from dataclasses_json import DataClassJsonMixin, config

from ..input.property_input import PropertyInput


@dataclass(frozen=True)
class EditEquipmentInput(DataClassJsonMixin):
    id: str
    name: str
    properties: List[PropertyInput]
    deviceID: Optional[str] = None
    externalId: Optional[str] = None
