#!/usr/bin/env python3
# @generated AUTOGENERATED file. Do not Change!

from dataclasses import dataclass, field as _field
from functools import partial
from ...config import custom_scalars, datetime
from numbers import Number
from typing import Any, AsyncGenerator, Dict, List, Generator, Optional

from dataclasses_json import DataClassJsonMixin, config

from ..input.survey_template_question_input import SurveyTemplateQuestionInput


@dataclass(frozen=True)
class SurveyTemplateCategoryInput(DataClassJsonMixin):
    categoryTitle: str
    categoryDescription: str
    id: Optional[str] = None
    surveyTemplateQuestions: Optional[List[SurveyTemplateQuestionInput]] = None
