// Copyright (c) 2004-present Facebook All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"errors"
	"fmt"
	"math"

	"github.com/facebook/ent/dialect/sql"
	"github.com/facebook/ent/dialect/sql/sqlgraph"
	"github.com/facebook/ent/schema/field"
	"github.com/facebookincubator/symphony/pkg/ent/block"
	"github.com/facebookincubator/symphony/pkg/ent/entrypoint"
	"github.com/facebookincubator/symphony/pkg/ent/exitpoint"
	"github.com/facebookincubator/symphony/pkg/ent/predicate"
)

// EntryPointQuery is the builder for querying EntryPoint entities.
type EntryPointQuery struct {
	config
	limit      *int
	offset     *int
	order      []OrderFunc
	unique     []string
	predicates []predicate.EntryPoint
	// eager-loading edges.
	withPrevExitPoints *ExitPointQuery
	withParentBlock    *BlockQuery
	withFKs            bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the builder.
func (epq *EntryPointQuery) Where(ps ...predicate.EntryPoint) *EntryPointQuery {
	epq.predicates = append(epq.predicates, ps...)
	return epq
}

// Limit adds a limit step to the query.
func (epq *EntryPointQuery) Limit(limit int) *EntryPointQuery {
	epq.limit = &limit
	return epq
}

// Offset adds an offset step to the query.
func (epq *EntryPointQuery) Offset(offset int) *EntryPointQuery {
	epq.offset = &offset
	return epq
}

// Order adds an order step to the query.
func (epq *EntryPointQuery) Order(o ...OrderFunc) *EntryPointQuery {
	epq.order = append(epq.order, o...)
	return epq
}

// QueryPrevExitPoints chains the current query on the prev_exit_points edge.
func (epq *EntryPointQuery) QueryPrevExitPoints() *ExitPointQuery {
	query := &ExitPointQuery{config: epq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := epq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := epq.sqlQuery()
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(entrypoint.Table, entrypoint.FieldID, selector),
			sqlgraph.To(exitpoint.Table, exitpoint.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, entrypoint.PrevExitPointsTable, entrypoint.PrevExitPointsPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(epq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryParentBlock chains the current query on the parent_block edge.
func (epq *EntryPointQuery) QueryParentBlock() *BlockQuery {
	query := &BlockQuery{config: epq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := epq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := epq.sqlQuery()
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(entrypoint.Table, entrypoint.FieldID, selector),
			sqlgraph.To(block.Table, block.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, entrypoint.ParentBlockTable, entrypoint.ParentBlockColumn),
		)
		fromU = sqlgraph.SetNeighbors(epq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first EntryPoint entity in the query. Returns *NotFoundError when no entrypoint was found.
func (epq *EntryPointQuery) First(ctx context.Context) (*EntryPoint, error) {
	nodes, err := epq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{entrypoint.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (epq *EntryPointQuery) FirstX(ctx context.Context) *EntryPoint {
	node, err := epq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first EntryPoint id in the query. Returns *NotFoundError when no id was found.
func (epq *EntryPointQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = epq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{entrypoint.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (epq *EntryPointQuery) FirstIDX(ctx context.Context) int {
	id, err := epq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns the only EntryPoint entity in the query, returns an error if not exactly one entity was returned.
func (epq *EntryPointQuery) Only(ctx context.Context) (*EntryPoint, error) {
	nodes, err := epq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{entrypoint.Label}
	default:
		return nil, &NotSingularError{entrypoint.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (epq *EntryPointQuery) OnlyX(ctx context.Context) *EntryPoint {
	node, err := epq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID returns the only EntryPoint id in the query, returns an error if not exactly one id was returned.
func (epq *EntryPointQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = epq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{entrypoint.Label}
	default:
		err = &NotSingularError{entrypoint.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (epq *EntryPointQuery) OnlyIDX(ctx context.Context) int {
	id, err := epq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of EntryPoints.
func (epq *EntryPointQuery) All(ctx context.Context) ([]*EntryPoint, error) {
	if err := epq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return epq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (epq *EntryPointQuery) AllX(ctx context.Context) []*EntryPoint {
	nodes, err := epq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of EntryPoint ids.
func (epq *EntryPointQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := epq.Select(entrypoint.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (epq *EntryPointQuery) IDsX(ctx context.Context) []int {
	ids, err := epq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (epq *EntryPointQuery) Count(ctx context.Context) (int, error) {
	if err := epq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return epq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (epq *EntryPointQuery) CountX(ctx context.Context) int {
	count, err := epq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (epq *EntryPointQuery) Exist(ctx context.Context) (bool, error) {
	if err := epq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return epq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (epq *EntryPointQuery) ExistX(ctx context.Context) bool {
	exist, err := epq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the query builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (epq *EntryPointQuery) Clone() *EntryPointQuery {
	if epq == nil {
		return nil
	}
	return &EntryPointQuery{
		config:             epq.config,
		limit:              epq.limit,
		offset:             epq.offset,
		order:              append([]OrderFunc{}, epq.order...),
		unique:             append([]string{}, epq.unique...),
		predicates:         append([]predicate.EntryPoint{}, epq.predicates...),
		withPrevExitPoints: epq.withPrevExitPoints.Clone(),
		withParentBlock:    epq.withParentBlock.Clone(),
		// clone intermediate query.
		sql:  epq.sql.Clone(),
		path: epq.path,
	}
}

//  WithPrevExitPoints tells the query-builder to eager-loads the nodes that are connected to
// the "prev_exit_points" edge. The optional arguments used to configure the query builder of the edge.
func (epq *EntryPointQuery) WithPrevExitPoints(opts ...func(*ExitPointQuery)) *EntryPointQuery {
	query := &ExitPointQuery{config: epq.config}
	for _, opt := range opts {
		opt(query)
	}
	epq.withPrevExitPoints = query
	return epq
}

//  WithParentBlock tells the query-builder to eager-loads the nodes that are connected to
// the "parent_block" edge. The optional arguments used to configure the query builder of the edge.
func (epq *EntryPointQuery) WithParentBlock(opts ...func(*BlockQuery)) *EntryPointQuery {
	query := &BlockQuery{config: epq.config}
	for _, opt := range opts {
		opt(query)
	}
	epq.withParentBlock = query
	return epq
}

// GroupBy used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreateTime time.Time `json:"create_time,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.EntryPoint.Query().
//		GroupBy(entrypoint.FieldCreateTime).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (epq *EntryPointQuery) GroupBy(field string, fields ...string) *EntryPointGroupBy {
	group := &EntryPointGroupBy{config: epq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := epq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return epq.sqlQuery(), nil
	}
	return group
}

// Select one or more fields from the given query.
//
// Example:
//
//	var v []struct {
//		CreateTime time.Time `json:"create_time,omitempty"`
//	}
//
//	client.EntryPoint.Query().
//		Select(entrypoint.FieldCreateTime).
//		Scan(ctx, &v)
//
func (epq *EntryPointQuery) Select(field string, fields ...string) *EntryPointSelect {
	selector := &EntryPointSelect{config: epq.config}
	selector.fields = append([]string{field}, fields...)
	selector.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := epq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return epq.sqlQuery(), nil
	}
	return selector
}

func (epq *EntryPointQuery) prepareQuery(ctx context.Context) error {
	if epq.path != nil {
		prev, err := epq.path(ctx)
		if err != nil {
			return err
		}
		epq.sql = prev
	}
	if err := entrypoint.Policy.EvalQuery(ctx, epq); err != nil {
		return err
	}
	return nil
}

func (epq *EntryPointQuery) sqlAll(ctx context.Context) ([]*EntryPoint, error) {
	var (
		nodes       = []*EntryPoint{}
		withFKs     = epq.withFKs
		_spec       = epq.querySpec()
		loadedTypes = [2]bool{
			epq.withPrevExitPoints != nil,
			epq.withParentBlock != nil,
		}
	)
	if epq.withParentBlock != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, entrypoint.ForeignKeys...)
	}
	_spec.ScanValues = func() []interface{} {
		node := &EntryPoint{config: epq.config}
		nodes = append(nodes, node)
		values := node.scanValues()
		if withFKs {
			values = append(values, node.fkValues()...)
		}
		return values
	}
	_spec.Assign = func(values ...interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(values...)
	}
	if err := sqlgraph.QueryNodes(ctx, epq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}

	if query := epq.withPrevExitPoints; query != nil {
		fks := make([]driver.Value, 0, len(nodes))
		ids := make(map[int]*EntryPoint, len(nodes))
		for _, node := range nodes {
			ids[node.ID] = node
			fks = append(fks, node.ID)
			node.Edges.PrevExitPoints = []*ExitPoint{}
		}
		var (
			edgeids []int
			edges   = make(map[int][]*EntryPoint)
		)
		_spec := &sqlgraph.EdgeQuerySpec{
			Edge: &sqlgraph.EdgeSpec{
				Inverse: true,
				Table:   entrypoint.PrevExitPointsTable,
				Columns: entrypoint.PrevExitPointsPrimaryKey,
			},
			Predicate: func(s *sql.Selector) {
				s.Where(sql.InValues(entrypoint.PrevExitPointsPrimaryKey[1], fks...))
			},

			ScanValues: func() [2]interface{} {
				return [2]interface{}{&sql.NullInt64{}, &sql.NullInt64{}}
			},
			Assign: func(out, in interface{}) error {
				eout, ok := out.(*sql.NullInt64)
				if !ok || eout == nil {
					return fmt.Errorf("unexpected id value for edge-out")
				}
				ein, ok := in.(*sql.NullInt64)
				if !ok || ein == nil {
					return fmt.Errorf("unexpected id value for edge-in")
				}
				outValue := int(eout.Int64)
				inValue := int(ein.Int64)
				node, ok := ids[outValue]
				if !ok {
					return fmt.Errorf("unexpected node id in edges: %v", outValue)
				}
				edgeids = append(edgeids, inValue)
				edges[inValue] = append(edges[inValue], node)
				return nil
			},
		}
		if err := sqlgraph.QueryEdges(ctx, epq.driver, _spec); err != nil {
			return nil, fmt.Errorf(`query edges "prev_exit_points": %v`, err)
		}
		query.Where(exitpoint.IDIn(edgeids...))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			nodes, ok := edges[n.ID]
			if !ok {
				return nil, fmt.Errorf(`unexpected "prev_exit_points" node returned %v`, n.ID)
			}
			for i := range nodes {
				nodes[i].Edges.PrevExitPoints = append(nodes[i].Edges.PrevExitPoints, n)
			}
		}
	}

	if query := epq.withParentBlock; query != nil {
		ids := make([]int, 0, len(nodes))
		nodeids := make(map[int][]*EntryPoint)
		for i := range nodes {
			if fk := nodes[i].block_entry_point; fk != nil {
				ids = append(ids, *fk)
				nodeids[*fk] = append(nodeids[*fk], nodes[i])
			}
		}
		query.Where(block.IDIn(ids...))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			nodes, ok := nodeids[n.ID]
			if !ok {
				return nil, fmt.Errorf(`unexpected foreign-key "block_entry_point" returned %v`, n.ID)
			}
			for i := range nodes {
				nodes[i].Edges.ParentBlock = n
			}
		}
	}

	return nodes, nil
}

func (epq *EntryPointQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := epq.querySpec()
	return sqlgraph.CountNodes(ctx, epq.driver, _spec)
}

func (epq *EntryPointQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := epq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %v", err)
	}
	return n > 0, nil
}

func (epq *EntryPointQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   entrypoint.Table,
			Columns: entrypoint.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: entrypoint.FieldID,
			},
		},
		From:   epq.sql,
		Unique: true,
	}
	if ps := epq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := epq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := epq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := epq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector, entrypoint.ValidColumn)
			}
		}
	}
	return _spec
}

func (epq *EntryPointQuery) sqlQuery() *sql.Selector {
	builder := sql.Dialect(epq.driver.Dialect())
	t1 := builder.Table(entrypoint.Table)
	selector := builder.Select(t1.Columns(entrypoint.Columns...)...).From(t1)
	if epq.sql != nil {
		selector = epq.sql
		selector.Select(selector.Columns(entrypoint.Columns...)...)
	}
	for _, p := range epq.predicates {
		p(selector)
	}
	for _, p := range epq.order {
		p(selector, entrypoint.ValidColumn)
	}
	if offset := epq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := epq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// EntryPointGroupBy is the builder for group-by EntryPoint entities.
type EntryPointGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (epgb *EntryPointGroupBy) Aggregate(fns ...AggregateFunc) *EntryPointGroupBy {
	epgb.fns = append(epgb.fns, fns...)
	return epgb
}

// Scan applies the group-by query and scan the result into the given value.
func (epgb *EntryPointGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := epgb.path(ctx)
	if err != nil {
		return err
	}
	epgb.sql = query
	return epgb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (epgb *EntryPointGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := epgb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by. It is only allowed when querying group-by with one field.
func (epgb *EntryPointGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(epgb.fields) > 1 {
		return nil, errors.New("ent: EntryPointGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := epgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (epgb *EntryPointGroupBy) StringsX(ctx context.Context) []string {
	v, err := epgb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from group-by. It is only allowed when querying group-by with one field.
func (epgb *EntryPointGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = epgb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{entrypoint.Label}
	default:
		err = fmt.Errorf("ent: EntryPointGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (epgb *EntryPointGroupBy) StringX(ctx context.Context) string {
	v, err := epgb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by. It is only allowed when querying group-by with one field.
func (epgb *EntryPointGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(epgb.fields) > 1 {
		return nil, errors.New("ent: EntryPointGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := epgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (epgb *EntryPointGroupBy) IntsX(ctx context.Context) []int {
	v, err := epgb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from group-by. It is only allowed when querying group-by with one field.
func (epgb *EntryPointGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = epgb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{entrypoint.Label}
	default:
		err = fmt.Errorf("ent: EntryPointGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (epgb *EntryPointGroupBy) IntX(ctx context.Context) int {
	v, err := epgb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by. It is only allowed when querying group-by with one field.
func (epgb *EntryPointGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(epgb.fields) > 1 {
		return nil, errors.New("ent: EntryPointGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := epgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (epgb *EntryPointGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := epgb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from group-by. It is only allowed when querying group-by with one field.
func (epgb *EntryPointGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = epgb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{entrypoint.Label}
	default:
		err = fmt.Errorf("ent: EntryPointGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (epgb *EntryPointGroupBy) Float64X(ctx context.Context) float64 {
	v, err := epgb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by. It is only allowed when querying group-by with one field.
func (epgb *EntryPointGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(epgb.fields) > 1 {
		return nil, errors.New("ent: EntryPointGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := epgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (epgb *EntryPointGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := epgb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from group-by. It is only allowed when querying group-by with one field.
func (epgb *EntryPointGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = epgb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{entrypoint.Label}
	default:
		err = fmt.Errorf("ent: EntryPointGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (epgb *EntryPointGroupBy) BoolX(ctx context.Context) bool {
	v, err := epgb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (epgb *EntryPointGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range epgb.fields {
		if !entrypoint.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := epgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := epgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (epgb *EntryPointGroupBy) sqlQuery() *sql.Selector {
	selector := epgb.sql
	columns := make([]string, 0, len(epgb.fields)+len(epgb.fns))
	columns = append(columns, epgb.fields...)
	for _, fn := range epgb.fns {
		columns = append(columns, fn(selector, entrypoint.ValidColumn))
	}
	return selector.Select(columns...).GroupBy(epgb.fields...)
}

// EntryPointSelect is the builder for select fields of EntryPoint entities.
type EntryPointSelect struct {
	config
	fields []string
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Scan applies the selector query and scan the result into the given value.
func (eps *EntryPointSelect) Scan(ctx context.Context, v interface{}) error {
	query, err := eps.path(ctx)
	if err != nil {
		return err
	}
	eps.sql = query
	return eps.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (eps *EntryPointSelect) ScanX(ctx context.Context, v interface{}) {
	if err := eps.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from selector. It is only allowed when selecting one field.
func (eps *EntryPointSelect) Strings(ctx context.Context) ([]string, error) {
	if len(eps.fields) > 1 {
		return nil, errors.New("ent: EntryPointSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := eps.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (eps *EntryPointSelect) StringsX(ctx context.Context) []string {
	v, err := eps.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from selector. It is only allowed when selecting one field.
func (eps *EntryPointSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = eps.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{entrypoint.Label}
	default:
		err = fmt.Errorf("ent: EntryPointSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (eps *EntryPointSelect) StringX(ctx context.Context) string {
	v, err := eps.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from selector. It is only allowed when selecting one field.
func (eps *EntryPointSelect) Ints(ctx context.Context) ([]int, error) {
	if len(eps.fields) > 1 {
		return nil, errors.New("ent: EntryPointSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := eps.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (eps *EntryPointSelect) IntsX(ctx context.Context) []int {
	v, err := eps.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from selector. It is only allowed when selecting one field.
func (eps *EntryPointSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = eps.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{entrypoint.Label}
	default:
		err = fmt.Errorf("ent: EntryPointSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (eps *EntryPointSelect) IntX(ctx context.Context) int {
	v, err := eps.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from selector. It is only allowed when selecting one field.
func (eps *EntryPointSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(eps.fields) > 1 {
		return nil, errors.New("ent: EntryPointSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := eps.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (eps *EntryPointSelect) Float64sX(ctx context.Context) []float64 {
	v, err := eps.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from selector. It is only allowed when selecting one field.
func (eps *EntryPointSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = eps.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{entrypoint.Label}
	default:
		err = fmt.Errorf("ent: EntryPointSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (eps *EntryPointSelect) Float64X(ctx context.Context) float64 {
	v, err := eps.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from selector. It is only allowed when selecting one field.
func (eps *EntryPointSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(eps.fields) > 1 {
		return nil, errors.New("ent: EntryPointSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := eps.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (eps *EntryPointSelect) BoolsX(ctx context.Context) []bool {
	v, err := eps.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from selector. It is only allowed when selecting one field.
func (eps *EntryPointSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = eps.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{entrypoint.Label}
	default:
		err = fmt.Errorf("ent: EntryPointSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (eps *EntryPointSelect) BoolX(ctx context.Context) bool {
	v, err := eps.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (eps *EntryPointSelect) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range eps.fields {
		if !entrypoint.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for selection", f)}
		}
	}
	rows := &sql.Rows{}
	query, args := eps.sqlQuery().Query()
	if err := eps.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (eps *EntryPointSelect) sqlQuery() sql.Querier {
	selector := eps.sql
	selector.Select(selector.Columns(eps.fields...)...)
	return selector
}
