{
 "title": "Symphony GraphQL Endpoints",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Interval",
    "label": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "Tenant",
    "query": "label_values(graphql_server_resolve_count_by_object_field, viewer_tenant)\t"
   }
  ]
 },
 "panels": [
  {
   "title": "GraphQL Mutations",
   "type": "table",
   "gridPos": { "h": 14, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sort(sum by (graphql_field, viewer_user_agent) (increase(graphql_server_resolve_count_by_object_field{viewer_tenant=\"$Tenant\", graphql_object=\"Mutation\"}[$Interval])) != 0)",
     "legendFormat": "{{graphql_object}},{{graphql_field}},{{viewer_user_agent}}"
    }
   ]
  },
  {
   "title": "GraphQL Deprecated Fields",
   "type": "table",
   "gridPos": { "h": 14, "w": 11, "x": 11, "y": 0 },
   "targets": [
    {
     "expr": "sort(sum by (graphql_object, graphql_field, viewer_user_agent) (increase(graphql_server_resolve_count_by_object_field{viewer_tenant=\"$Tenant\",graphql_deprecated=\"true\"}[$Interval])) != 0)",
     "legendFormat": "{{graphql_object}},{{graphql_field}},{{viewer_user_agent}}"
    }
   ]
  },
  {
   "title": "GraphQL Deprecated Input Fields",
   "type": "table",
   "gridPos": { "h": 14, "w": 11, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sort(sum by (graphql_field, viewer_user_agent) (increase(graphql_server_deprecated_count_by_object_input_field{viewer_tenant=\"$Tenant\"}[$Interval])) != 0)",
     "legendFormat": "{{graphql_object}},{{graphql_field}},{{viewer_user_agent}}"
    }
   ]
  },
  {
   "title": "GraphQL Deprecated Fields Over Time",
   "type": "graph",
   "gridPos": { "h": 14, "w": 11, "x": 11, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (graphql_object, graphql_field) (increase(graphql_server_resolve_count_by_object_field{viewer_tenant=\"$Tenant\",graphql_deprecated=\"true\"}[$Interval]))",
     "legendFormat": "{{graphql_object}}.{{graphql_field}}"
    }
   ]
  }
 ]
}