{
 "title": "Symphony / GraphQL",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": "label_values(graphql_requests_total, namespace)"
   },
   {
    "name": "container",
    "query": "label_values(graphql_requests_total{namespace=~\"$namespace\"}, container)"
   },
   {
    "name": "tenant",
    "query": "label_values(graphql_requests_total{namespace=~\"$namespace\"}, viewer_tenant)"
   },
   { "name": "operation", "query": "mutation,query,subscription" }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests Volume",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "round(sum(irate(graphql_requests_total{namespace=\"$namespace\", container=~\"$container\", viewer_tenant=~\"$tenant\"}[$__rate_interval])), 0.001)"
    }
   ]
  },
  {
   "title": "Current Subscriptions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(avg_over_time(graphql_current_subscriptions{namespace=\"$namespace\", container=~\"$container\", viewer_tenant=~\"$tenant\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Success Rate (responses without errors)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(graphql_responses_total{namespace=\"$namespace\", container=~\"$container\", viewer_tenant=~\"$tenant\", operation=~\"$operation\", errors=\"0\"}[$__rate_interval])) / sum(rate(graphql_responses_total{namespace=\"$namespace\", container=~\"$container\", viewer_tenant=~\"$tenant\", operation=~\"$operation\"}[$__rate_interval]))"
    }
   ]
  },
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Requests Per Second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "round(sum(irate(graphql_requests_total{namespace=\"$namespace\", container=~\"$container\", viewer_tenant=~\"$tenant\", operation=~\"$operation\"}[$__rate_interval])) by (viewer_tenant), 0.001)",
     "legendFormat": "{{ viewer_tenant }}"
    }
   ]
  },
  {
   "title": "Request Times",
   "type": "table",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(graphql_request_latency_milliseconds_bucket{namespace=\"$namespace\", container=~\"$container\"}[$__rate_interval])) by (viewer_tenant, le)) > 0",
     "legendFormat": "{{ viewer_tenant }}"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(graphql_request_latency_milliseconds_bucket{namespace=~\"$namespace\", container=~\"$container\"}[$__rate_interval])) by (viewer_tenant, le)) > 0",
     "legendFormat": "{{ viewer_tenant }}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(graphql_request_latency_milliseconds_bucket{namespace=~\"$namespace\", container=~\"$container\"}[$__rate_interval])) by (viewer_tenant, le)) > 0",
     "legendFormat": "{{ viewer_tenant }}"
    }
   ]
  },
  {
   "title": "Request Complexities",
   "type": "graph",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(1, sum(rate(graphql_request_complexities_bucket{namespace=~\"$namespace\", viewer_tenant=~\"$tenant\"}[$__rate_interval])) by (viewer_tenant, le))",
     "legendFormat": "{{ viewer_tenant }}"
    }
   ]
  },
  { "title": "Responses", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Responses Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(1, sum(rate(graphql_response_bytes_bucket{namespace=\"$namespace\", container=~\"$container\", viewer_tenant=~\"$tenant\"}[$__rate_interval])) by (viewer_tenant, le)) / 1024",
     "legendFormat": "{{ viewer_tenant }}"
    }
   ]
  },
  {
   "title": "Response Errors Per Minute",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(graphql_responses_total{namespace=\"$namespace\", container=~\"$container\", viewer_tenant=~\"$tenant\", operation=~\"$operation\", errors!=\"0\"}[$__rate_interval])) by (viewer_tenant) * 60",
     "legendFormat": "{{ viewer_tenant }}"
    }
   ]
  },
  { "title": "Resolves", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Resolves Per Second",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "round(sum(irate(graphql_resolves_total{namespace=\"$namespace\", container=~\"$container\", viewer_tenant=~\"$tenant\"}[$__rate_interval])) by (viewer_tenant), 0.001)",
     "legendFormat": "{{ viewer_tenant }}"
    }
   ]
  },
  {
   "title": "Resolve Times",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(graphql_resolve_latency_milliseconds_bucket{namespace=\"$namespace\", container=~\"$container\"}[$__rate_interval])) by (viewer_tenant, le)) > 0",
     "legendFormat": "{{ viewer_tenant }}"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(graphql_resolve_latency_milliseconds_bucket{namespace=~\"$namespace\", container=~\"$container\"}[$__rate_interval])) by (viewer_tenant, le)) > 0",
     "legendFormat": "{{ viewer_tenant }}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(graphql_resolve_latency_milliseconds_bucket{namespace=~\"$namespace\", container=~\"$container\"}[$__rate_interval])) by (viewer_tenant, le)) > 0",
     "legendFormat": "{{ viewer_tenant }}"
    }
   ]
  },
  {
   "title": "Deprecated Fields",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "targets": [
    {
     "expr": "sum(graphql_deprecated_resolves_total) by (viewer_tenant, object, field)"
    }
   ]
  }
 ]
}