#!/usr/bin/env python3
# @generated AUTOGENERATED file. Do not Change!

from dataclasses import dataclass, field as _field
from functools import partial
from ...config import custom_scalars, datetime
from numbers import Number
from typing import Any, AsyncGenerator, Dict, List, Generator, Optional

from dataclasses_json import DataClassJsonMixin, config

from ..input.variable_expression_input import VariableExpressionInput


@dataclass(frozen=True)
class DecisionRouteInput(DataClassJsonMixin):
    condition: VariableExpressionInput
    cid: Optional[str] = None
